[project]
name = "snipster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sl2902", email = "laxmsun@hotmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
snipster = "snipster:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
